spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niumo_database
    username: root
    password: 123654


mybatis:
  configuration:
    map-underscore-to-camel-case: true
